### ISSUE TITLE
OpenNN cloning

### ISSUE THREAD

**Issue by YsfHam** [wagnrd/Pong#1]
Hi,
I have an issue when cloning your project with --recurse-submodules, the openNN library folder is empty so I couldn't build your project with cmake.

**Comment by wagnrd** [comment]
Hi YsfHam,
Thank you for pointing this out!
I fixed everything and included OpenNN into this repo.
I also added some stuff to the dependencies section in case you also had trouble with this.

I hope everything will work now :)

**Comment by YsfHam** [comment]
Thank you very much.
